version: "3.9"
services:
  express-backend:
    build:
      context: ./express-backend/.
      dockerfile: Dockerfile.production
    ports:
      - "8000:8888"

  react-nginx-server:
    build:
      context: ./react-frontend/.
      dockerfile: Dockerfile.production
    ports:
      - "90:80"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: --quiet --logpath /dev/null